Fix bug where `tags` directory causes error
Fix a bug where the presence of a `tags` directory causes the error:

    Error: EISDIR: illegal operation on a directory, read